"use client"

import { motion } from "framer-motion"

export default function GallerySection() {
  const images = [
    {
      src: "/placeholder.svg?height=300&width=400",
      alt: "Coastal landscape",
    },
    {
      src: "/placeholder.svg?height=300&width=400",
      alt: "Vintage cars",
      caption: "48,000",
      subcaption: "IMAGES GENERATED BY ARTIFICIAL INTELLIGENCE",
    },
    {
      src: "/placeholder.svg?height=300&width=400",
      alt: "Snowy landscape",
    },
    {
      src: "/placeholder.svg?height=300&width=400",
      alt: "Colorful architecture",
    },
  ]

  return (
    <section className="py-16 px-8 md:px-16 relative">
      <motion.h2
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.7 }}
        className="text-3xl md:text-4xl font-bold mb-12"
      >
        Journey Through Art of community
      </motion.h2>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {images.map((image, index) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: index * 0.1 }}
            whileHover={{ y: -5 }}
            className="relative rounded-lg overflow-hidden"
          >
            <img src={image.src || "/placeholder.svg"} alt={image.alt} className="w-full h-[250px] object-cover" />
            {image.caption && (
              <div className="absolute inset-0 flex flex-col justify-end p-4 bg-gradient-to-t from-black/80 to-transparent">
                <p className="text-2xl font-bold text-secondary-lime">{image.caption}</p>
                <p className="text-xs text-white/80">{image.subcaption}</p>
              </div>
            )}
          </motion.div>
        ))}
      </div>
    </section>
  )
}
